# Generated by Django 5.2.10 on 2026-01-29 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='pharmacy_ph_name_cb0bc9_idx'), models.Index(fields=['is_active'], name='pharmacy_ph_is_acti_f59ca5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('prescription_required', models.BooleanField(default=False)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='pharmacy.pharmacy')),
            ],
            options={
                'indexes': [models.Index(fields=['pharmacy', 'name'], name='pharmacy_me_pharmac_cbdd77_idx'), models.Index(fields=['prescription_required'], name='pharmacy_me_prescri_2b2670_idx')],
            },
        ),
    ]
