# Generated by Django 6.0.1 on 2026-01-31 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pharmacies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='pharmacy',
            index=models.Index(fields=['owner'], name='pharmacy_ph_owner_i_a034fd_idx'),
        ),
    ]
