# Generated by Django 6.0.1 on 2026-01-31 14:10

import uuid

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0002_pharmacy_owner_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pharmacy",
            old_name="location",
            new_name="address",
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="license_number",
            field=models.CharField(
                blank=True,
                help_text="Government-issued pharmacy license number.",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="contact_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="contact_phone",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="owner_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="owner_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="owner_phone",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="verification_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="verification_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="pharmacy",
            index=models.Index(fields=["is_verified"], name="pharmacy_ph_is_ver_b7cb1d_idx"),
        ),
    ]
